services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"