name: Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run offline unit tests
        run: |
          echo 'Running offline unit tests that require no external dependencies...'
          cd tests
          python -m pytest test_receipt_fields.py -v
          python -m pytest test_receipt_processing.py -v  
          python -m pytest test_normalize_totals_standalone.py -v

      - name: Run syntax and import checks
        env:
          JWT_SECRET: "test-secret-for-import-only"
          DATABASE_URL: "postgresql://test:test@localhost:5432/test"
          OUTLOOK_CLIENT_ID: "test-client-id"
          OUTLOOK_TENANT_ID: "consumers"
          OUTLOOK_REDIRECT_URI: "https://login.microsoftonline.com/common/oauth2/nativeclient"
        run: |
          echo 'Checking Python syntax and imports...'
          python -m py_compile backend/app/main.py
          python -m py_compile backend/app/models.py
          python -m py_compile backend/app/schemas.py
          python -m py_compile backend/app/database.py
          python -c "import sys; sys.path.append('backend'); from app.routes import receipts, auth, dashboard, outlook, transactions; print('All route imports successful')"

      - name: Cleanup
        run: |
          echo 'Test run completed successfully!'
